version: '2' 
services: 
  elasticsearch: 
    image: "elasticsearch:1.7" 
    command: "elasticsearch -Dcluster.name=hesperides" 
  redis: 
    image: "redis" 
  hesperides: 
    image: "hesperides/hesperides:demo-chaos"
    ports: 
      - "8080:8080"
    depends_on:
      - elasticsearch
      - redis
  gradle-test:
    build:
      context: .
    depends_on:
      - hesperides
    environment:
      - HESPERIDES_HOST=hesperides
      - HESPERIDES_PORT=8080
